### ISSUE TITLE
[BUG] Trim fails on 3.3 LTS

### ISSUE THREAD

**Issue by diramazioni** [hlorus/CAD_Sketcher#295]
### Description

`Error: Python: Traceback (most recent call last):
  File "/home/es/.config/blender/3.3/scripts/addons/CAD_Sketcher-main/stateful_operator/logic.py", line 472, in modal
    return self.evaluate_state(context, event, event_triggered)
  File "/home/es/.config/blender/3.3/scripts/addons/CAD_Sketcher-main/stateful_operator/logic.py", line 554, in evaluate_state
    return self._end(context, succeede)
  File "/home/es/.config/blender/3.3/scripts/addons/CAD_Sketcher-main/stateful_operator/logic.py", line 615, in _end
    self.fini(context, succeede)
  File "/home/es/.config/blender/3.3/scripts/addons/CAD_Sketcher-main/operators/trim.py", line 63, in fini
    if not type(e) in segment:
TypeError: bpy_struct.__contains__: expected a string
`

### Addon Version

0.25.0

### Blender Version

3.3

### What platform are you running on?

Linux

**Comment by hlorus** [comment]
My bad, that was an oversight while cleaning up, should be fixed by https://github.com/hlorus/CAD_Sketcher/commit/fc9bb43aebd46ad62b71913521383be2322a0f34.

Thanks for reporting!
