### ISSUE TITLE
[BUG] Trim between tanget

### ISSUE THREAD

**Issue by vbernado** [hlorus/CAD_Sketcher#385]
### Contact Details

vbernado@gmail.com

### Description

I put a Circle into a Rectangle, I make it tangent at one corner (two tangent constraint), and when I try to Trim the inner arc throw  this exception:
`bpy.ops.view3d.slvs_trim(wait_for_input=False, sketch_i=4194304)
Python: Traceback (most recent call last):
  File "C:\Users\78095166T\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\CAD_Sketcher-main\stateful_operator\logic.py", line 481, in modal
    return self.evaluate_state(context, event, event_triggered)
  File "C:\Users\78095166T\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\CAD_Sketcher-main\stateful_operator\logic.py", line 564, in evaluate_state
    return self._end(context, succeede)
  File "C:\Users\78095166T\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\CAD_Sketcher-main\stateful_operator\logic.py", line 625, in _end
    self.fini(context, succeede)
  File "C:\Users\78095166T\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\CAD_Sketcher-main\operators\trim.py", line 84, in fini
    if not trim.check():
  File "C:\Users\78095166T\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\CAD_Sketcher-main\utilities\trimming.py", line 80, in check
    relevant = self.relevant_intersections()
  File "C:\Users\78095166T\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\CAD_Sketcher-main\utilities\trimming.py", line 100, in relevant_intersections
    closest = ordered[0].index, ordered[-1].index
IndexError: list index out of range
![image](https://github.com/hlorus/CAD_Sketcher/assets/129081209/4ce1748d-256e-4771-ac20-f0bdb436aed5)
` 

### Addon Version

0.27.1

### Blender Version

3.5.1

### What platform are you running on?

Windows

**Comment by vbernado** [comment]
Not a bug.
I think that tangent create a pont in the tangent point, but it doesn't do, and that's the reason because trim not work.
If I and a point with coincident constraint on circle and on line too, it work properly

Thank for work
