### ISSUE TITLE
[BUG] ImportError: cannot import name 'GPUShaderCreateInfo' from 'gpu.types' (unknown location)

### ISSUE THREAD

**Issue by icarosadero** [hlorus/CAD_Sketcher#466]
### Description

I installed the zip as instructed in the README and got the following error while trying it activate it:

I'm on Linux - Kubuntu 22.04.4

```
Color management: using fallback mode for management
Color management: Error could not find role data role.
Read prefs: /home/user/.config/blender/3.0/config/userpref.blend
Color management: scene view "Filmic" not found, setting default "Standard".
Traceback (most recent call last):
  File "/usr/share/blender/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/user/.config/blender/3.0/scripts/addons/CAD_Sketcher-main/__init__.py", line 29, in <module>
    from .registration import register_base, unregister_base, register_full, unregister_full
  File "/home/user/.config/blender/3.0/scripts/addons/CAD_Sketcher-main/registration.py", line 21, in <module>
    register_full, unregister_full = module_register_factory(__package__, core_modules)
  File "/home/user/.config/blender/3.0/scripts/addons/CAD_Sketcher-main/utilities/register.py", line 29, in module_register_factory
    modules = [
  File "/home/user/.config/blender/3.0/scripts/addons/CAD_Sketcher-main/utilities/register.py", line 30, in <listcomp>
    importlib.import_module(f"{parent_module_name}.{name}") for name in module_names
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/.config/blender/3.0/scripts/addons/CAD_Sketcher-main/model/__init__.py", line 34, in <module>
    register, unregister = module_register_factory(__name__, modules)
  File "/home/user/.config/blender/3.0/scripts/addons/CAD_Sketcher-main/utilities/register.py", line 29, in module_register_factory
    modules = [
  File "/home/user/.config/blender/3.0/scripts/addons/CAD_Sketcher-main/utilities/register.py", line 30, in <listcomp>
    importlib.import_module(f"{parent_module_name}.{name}") for name in module_names
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/.config/blender/3.0/scripts/addons/CAD_Sketcher-main/model/point_3d.py", line 11, in <module>
    from .base_entity import SlvsGenericEntity
  File "/home/user/.config/blender/3.0/scripts/addons/CAD_Sketcher-main/model/base_entity.py", line 10, in <module>
    from ..shaders import Shaders
  File "/home/user/.config/blender/3.0/scripts/addons/CAD_Sketcher-main/shaders.py", line 2, in <module>
    from gpu.types import GPUShader, GPUShaderCreateInfo, GPUStageInterfaceInfo
ImportError: cannot import name 'GPUShaderCreateInfo' from 'gpu.types' (unknown location)
```

### Addon Version

0.27.3

### Blender Version

3.0.1

### What platform are you running on?

Linux

**Comment by hlorus** [comment]
As stated in the readme the minimal blender version is 3.3, please update blender to use the addon.
