### ISSUE TITLE
[BUG] TypeError: Cannot assign a 'Object' value to the existing 'target_curve_object' Group IDProperty

### ISSUE THREAD

**Issue by bmurphy1976** [hlorus/CAD_Sketcher#475]
### Description

I'm getting the following error when trying to extrude a simple rectangle sketch.  I have no constraints or any other complications and I still get the same error.

```
Traceback (most recent call last):
  File "/Users/bmurphy/Library/Application Support/Blender/4.2/scripts/addons/CAD_Sketcher-main/operators/set_sketch.py", line 20, in execute
    return activate_sketch(context, self.index, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bmurphy/Library/Application Support/Blender/4.2/scripts/addons/CAD_Sketcher-main/operators/utilities.py", line 186, in activate_sketch
    update_convertor_geometry(context.scene, sketch=last_sketch)
  File "/Users/bmurphy/Library/Application Support/Blender/4.2/scripts/addons/CAD_Sketcher-main/converters.py", line 135, in update_convertor_geometry
    sketch.target_curve_object = object
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bmurphy/Library/Application Support/Blender/4.2/scripts/addons/CAD_Sketcher-main/utilities/bpy.py", line 85, in unique_attribute_setter
    self[name] = value
    ~~~~^^^^^^
TypeError: Cannot assign a 'Object' value to the existing 'target_curve_object' Group IDProperty
Error: Python: Traceback (most recent call last):
  File "/Users/bmurphy/Library/Application Support/Blender/4.2/scripts/addons/CAD_Sketcher-main/operators/set_sketch.py", line 20, in execute
    return activate_sketch(context, self.index, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bmurphy/Library/Application Support/Blender/4.2/scripts/addons/CAD_Sketcher-main/operators/utilities.py", line 186, in activate_sketch
    update_convertor_geometry(context.scene, sketch=last_sketch)
  File "/Users/bmurphy/Library/Application Support/Blender/4.2/scripts/addons/CAD_Sketcher-main/converters.py", line 135, in update_convertor_geometry
    sketch.target_curve_object = object
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bmurphy/Library/Application Support/Blender/4.2/scripts/addons/CAD_Sketcher-main/utilities/bpy.py", line 85, in unique_attribute_setter
    self[name] = value
    ~~~~^^^^^^
TypeError: Cannot assign a 'Object' value to the existing 'target_curve_object' Group IDProperty
[SCScene :: ViewLayer]: Removed 6 relations to no-op nodes
```
<img width="1387" alt="Screenshot 2024-08-19 at 6 50 29 PM" src="https://github.com/user-attachments/assets/62aeb772-3727-448f-a57c-95f1dd5e4ce8">
<img width="1385" alt="Screenshot 2024-08-19 at 6 50 47 PM" src="https://github.com/user-attachments/assets/a7d57edb-cd76-4b0b-bf76-67da79347e8a">
<img width="1385" alt="Screenshot 2024-08-19 at 6 51 57 PM" src="https://github.com/user-attachments/assets/9cc91337-a626-438d-87ec-3637dea87511">
<img width="1387" alt="Screenshot 2024-08-19 at 6 52 07 PM" src="https://github.com/user-attachments/assets/9f21f76a-b2e6-426d-8c2e-006fd0dd9c63">

### Addon Version

0.27.3

### Blender Version

4.2.0

### What platform are you running on?

Mac OSX

**Comment by hlorus** [comment]
This is solved in the newest version, please get it from github.
