### ISSUE TITLE
ERROR Python: Traceback on one file only

### ISSUE THREAD

**Issue by fitaine** [hlorus/CAD_Sketcher#492]
My file was working fine and then I started to get an error when I tried to refresh sketches or add constraint to it. I think it has already happened to me previously but I was going back with a Ctrl+Z and it sorted things out. This time I may have not try to refresh the sketches for a while and didn't see the issue immediately, so it was impossible to going back.

- Blender version is 3.6.9
- CAD_Sketcher version is 0.27.5
- No problem on other .blend files
- Link to the problematic .blend file :  [https://transfert.free.fr/rX6U9Pw](https://transfert.free.fr/rX6U9Pw)

Here is what I get:

```
Python: Traceback (most recent call last):
  File "/Users/Tiphaine/Library/Application Support/Blender/3.6/scripts/addons/CAD_Sketcher-main/operators/solve.py", line 18, in execute
    ok = solver.solve()
  File "/Users/Tiphaine/Library/Application Support/Blender/3.6/scripts/addons/CAD_Sketcher-main/solver.py", line 197, in solve
    self._init_slvs_data()
  File "/Users/Tiphaine/Library/Application Support/Blender/3.6/scripts/addons/CAD_Sketcher-main/solver.py", line 102, in _init_slvs_data
    e.create_slvs_data(self.solvesys, group=group)
  File "/Users/Tiphaine/Library/Application Support/Blender/3.6/scripts/addons/CAD_Sketcher-main/model/workplane.py", line 97, in create_slvs_data
    handle = solvesys.addWorkplane(self.p1.py_data, self.nm.py_data, group=group)
  File "/Users/Tiphaine/Library/Application Support/Blender/3.6/scripts/addons/CAD_Sketcher-main/model/base_entity.py", line 101, in py_data
    return global_data.entities[self.slvs_index]
KeyError: 5242884
```

I hope someone could help me on this one, because I spend some time on it. I really like to understand what I did that led to this problem.

**Comment by hlorus** [comment]
This refresh/add-constraint traceback is from the pre-rewrite converter path, which has been removed (mesh conversion now runs through Geometry Nodes) - the same family as the fixed #496. The linked file host has expired. Please retest on the latest prerelease build and reopen with a .blend if it persists.
