### ISSUE TITLE
[BUG] Unhandled exception on sketch update/leave (solver?)

### ISSUE THREAD

**Issue by MilanV** [hlorus/CAD_Sketcher#496]
### Contact Details

milan@caputu.cz

### Description

During my work on a sketch, some objects (e.g. lines) started causing an exception. Sketch editing works as usual, just if I try to leave the sketch or "force update" it, the addon fails with unhandled exception:

```
Traceback (most recent call last):
  File "/home/milan/.config/blender/3.4/scripts/addons/CAD_Sketcher-main/operators/update.py", line 19, in execute
    update_convertor_geometry(context.scene)
  File "/home/milan/.config/blender/3.4/scripts/addons/CAD_Sketcher-main/converters.py", line 146, in update_convertor_geometry
    conv = BezierConverter(scene, sketch)
  File "/home/milan/.config/blender/3.4/scripts/addons/CAD_Sketcher-main/converters.py", line 50, in to_bezier
    invert_direction = spline_path[1][i]
```

I added simple debug prints there to see which objects caused that:

```
CAD_Sketcher-main.converters:{DEBUG}: Index error spline_path[1][0]
CAD_Sketcher-main.converters:{DEBUG}: Index error: spline_path=([bpy.data.scenes['Scene'].sketcher.entities.lines2D[154]], []): 
CAD_Sketcher-main.converters:{DEBUG}: Index error spline_path[1][0]
CAD_Sketcher-main.converters:{DEBUG}: Index error: spline_path=([bpy.data.scenes['Scene'].sketcher.entities.lines2D[156]], []): 
CAD_Sketcher-main.converters:{DEBUG}: Index error spline_path[1][0]
CAD_Sketcher-main.converters:{DEBUG}: Index error: spline_path=([bpy.data.scenes['Scene'].sketcher.entities.lines2D[158]], []): 
```

See, the second item of spline_path is an empty array for each such object (lines2D).

As a sketch editing works without problems, I cannot say when the problem started and why. Only I can say is that I cannot see those lines highlighted if I select them in the list of entities. Lines of zero length? Ghost lines having no length and no endpoints?

So, in fact, there are two bugs: the visible error/exception and the GUI creating those problematic objects...

In the attached file, it is in the sketch kuk2.
[kukatko1.blend.gz](https://github.com/user-attachments/files/18114267/kukatko1.blend.gz)

### Addon Version

0.27.5

### Blender Version

3.4.1

### What platform are you running on?

Linux

**Comment by hlorus** [comment]
Likely fixed by the native-curves rewrite, which reworked the data model and mesh conversion and cleared a batch of crashes and reload/persistence bugs. Please retest against the latest prerelease build. If it still happens, reopen with a sample .blend and the full traceback.
